### ISSUE TITLE
If you click a company from the sidebar, zoom into it's location

### ISSUE THREAD

**Issue by sydmclean** [mcleantom/cgtmappapp#30]
b.c. now it doesn't do anything useful

**Comment by mcleantom** [comment]
because you deleted the code for it

**Comment by sydmclean** [comment]
ik haha

**Comment by sydmclean** [comment]
but i guess zoom in only if you clicked on it from the company sidebar

but it works good atm for if you're just scrolling around browsing for companies

**Comment by sydmclean** [comment]
sorry uwu

**Comment by mcleantom** [comment]
> sorry uwu

oopsy woopsy made a fucky wucky
